steps:
  # reservations
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-reservations'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleeper-446416/reservations/production',
        '-f',
        'apps/reservations/Dockerfile',
        '.',
      ]
    waitFor: ['-'] # The '-' indicates that this step begins immediately.
 
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-reservations'
    args:
      [
        'push',
        'us-east4-docker.pkg.dev/sleeper-446416/reservations/production',
      ]
    waitFor: ['build-reservations']
 
  # auth
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-auth'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/sleeper-446416/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.',
      ]
    waitFor: ['-'] # The '-' indicates that this step begins immediately.

logsBucket: "gs://sleepr-logs" # logs bucket

